create table cliente (
	codcliente INT PRIMARY KEY,
	nome VARCHAR(50),
	sexo VARCHAR(50),
	dt_nascimento DATE,
	bairro VARCHAR(23)
);
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (1, 'Jillie Lupson', 'F', '1994-06-17', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (2, 'Jesse McCutcheon', 'M', '1987-06-29', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (3, 'Aliza Crowth', 'F', '1971-10-25', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (4, 'Bella Oubridge', 'F', '1968-02-27', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (5, 'Joseph Zanettini', 'M', '1979-02-10', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (6, 'Kynthia Worcs', 'F', '1969-08-07', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (7, 'Paulo Fairpool', 'M', '1970-05-11', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (8, 'Rooney Brecknell', 'M', '1978-03-02', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (9, 'Biron Hay', 'M', '1974-09-26', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (10, 'Latisha Thornton', 'F', '1983-11-21', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (11, 'Carmon Genthner', 'F', '1980-10-17', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (12, 'Kirsti Filippucci', 'F', '1998-12-03', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (13, 'Dale Lagde', 'F', '1980-11-27', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (14, 'Lib Sails', 'F', '1992-08-26', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (15, 'Bellanca Grundle', 'F', '1979-10-19', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (16, 'Gerry Weafer', 'F', '1975-09-23', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (17, 'Hildegarde Waliszewski', 'F', '1993-10-25', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (18, 'Shelley Quye', 'M', '1994-04-06', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (19, 'Blakeley Benkhe', 'F', '1982-10-05', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (20, 'Gibbie Bertelmot', 'M', '1987-11-15', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (21, 'Leif Trosdall', 'M', '1990-11-29', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (22, 'Jaquelyn Segebrecht', 'F', '1988-01-22', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (23, 'Sibylla Cockrill', 'F', '1972-04-11', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (24, 'Bailey Learmount', 'M', '1984-05-26', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (25, 'Morry Entres', 'M', '1989-04-21', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (26, 'Abrahan Gritsunov', 'M', '1982-05-22', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (27, 'Leroy Beswell', 'M', '1996-01-08', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (28, 'Jackson Hains', 'M', '1975-11-26', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (29, 'Yolande Ivimey', 'F', '1988-12-03', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (30, 'Loraine Pincked', 'F', '1995-08-12', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (31, 'Henri Mohring', 'M', '1970-06-09', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (32, 'Hilda Parmby', 'F', '1993-11-14', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (33, 'Janna Jenks', 'F', '1990-11-17', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (34, 'Brocky McJury', 'M', '1999-05-19', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (35, 'Allin Walewicz', 'M', '1980-12-02', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (36, 'Nate Cardinal', 'M', '1994-10-09', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (37, 'Farr Josefson', 'M', '1988-12-06', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (38, 'Marchall Blumsom', 'M', '1969-06-04', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (39, 'Alastair Cossor', 'M', '1972-03-16', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (40, 'Murvyn Cumberbatch', 'M', '1988-06-05', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (41, 'Demetri Thame', 'M', '1981-12-22', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (42, 'Maudie Wilhelmy', 'F', '1998-01-09', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (43, 'Ulberto Goldingay', 'M', '1998-04-15', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (44, 'Carole Windless', 'F', '1987-04-17', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (45, 'Niels Meadows', 'M', '1968-02-21', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (46, 'Prisca Gobell', 'F', '1974-04-14', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (47, 'Kalle Le Moucheux', 'M', '1974-09-22', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (48, 'Freedman Coley', 'M', '1984-06-21', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (49, 'Meredith Hartwell', 'M', '1977-12-17', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (50, 'Jerrie Antonomolii', 'M', '1984-12-02', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (51, 'Katharina Earnshaw', 'F', '1990-07-14', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (52, 'Erna MacSkeaghan', 'F', '1967-10-21', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (53, 'Eddi Silverthorn', 'F', '1994-09-15', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (54, 'Cristie Jemmison', 'F', '1981-05-29', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (55, 'Ryon Vaugham', 'M', '1994-04-15', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (56, 'Emile Truman', 'M', '1981-02-21', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (57, 'Shane Kelway', 'F', '1967-02-21', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (58, 'Scotti Spafford', 'M', '1990-02-23', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (59, 'Glynn Figin', 'M', '1997-02-16', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (60, 'Hamish Condliffe', 'M', '1978-11-16', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (61, 'Mindy Hembry', 'F', '1981-03-02', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (62, 'Nickola Aguirre', 'M', '1974-03-11', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (63, 'Maribeth Laise', 'F', '1976-12-12', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (64, 'Alonso Castillon', 'M', '1999-09-01', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (65, 'Larine Tolefree', 'F', '1999-10-07', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (66, 'Mufinella Poytheras', 'F', '1996-03-30', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (67, 'Tod Favela', 'M', '1997-04-03', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (68, 'Amity Josefsohn', 'F', '1988-04-18', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (69, 'Stesha Rockingham', 'F', '1986-10-31', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (70, 'Jefferey Elphey', 'M', '1994-11-21', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (71, 'Gerik Dumbreck', 'M', '1975-11-27', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (72, 'Alexio Sprulls', 'M', '1988-01-26', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (73, 'Drud Durrett', 'M', '1999-04-10', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (74, 'Wright Monget', 'M', '1978-07-11', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (75, 'Sophie Chater', 'F', '1985-01-26', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (76, 'Francklin Southerden', 'M', '1992-06-21', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (77, 'Reamonn Benfield', 'M', '1968-12-02', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (78, 'Jorrie Swafford', 'F', '1978-09-27', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (79, 'Otto Skelly', 'M', '1987-10-20', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (80, 'Monro Torres', 'M', '1998-03-07', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (81, 'Yuma Stolworthy', 'M', '1994-10-24', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (82, 'Welch Bayless', 'M', '1981-01-28', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (83, 'Woodrow Stair', 'M', '1972-01-19', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (84, 'Reggy Dawltrey', 'M', '1971-01-27', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (85, 'Creight Moller', 'M', '1989-08-16', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (86, 'Saundra Kaygill', 'F', '1989-06-03', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (87, 'Graig Piggins', 'M', '1979-12-18', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (88, 'Jenelle Broodes', 'F', '1978-09-23', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (89, 'Vernor Careswell', 'M', '1974-03-22', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (90, 'Karie Pugh', 'F', '1991-01-28', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (91, 'Ellyn Kilroy', 'F', '1967-09-20', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (92, 'Violante Derrington', 'F', '1997-10-08', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (93, 'Sadella Snalum', 'F', '1986-11-04', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (94, 'Burr Benner', 'M', '1986-01-10', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (95, 'Inge Alberts', 'F', '1968-11-06', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (96, 'Jane Chetwind', 'F', '1977-02-05', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (97, 'Leonora Mottley', 'F', '1992-07-20', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (98, 'Dotty Krzyzowski', 'F', '1971-11-09', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (99, 'Ogden Shoutt', 'M', '1983-03-30', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (100, 'Babita Raffeorty', 'F', '1980-06-25', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (101, 'Dollie Mattessen', 'F', '1985-06-02', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (102, 'Moises Phipson', 'M', '1972-03-10', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (103, 'Richie Davies', 'M', '1990-10-27', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (104, 'Eduardo Espinola', 'M', '1977-08-18', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (105, 'Marnia Kittiman', 'F', '1981-07-25', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (106, 'Royall Llorente', 'M', '1968-09-08', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (107, 'Jacquetta Mityashev', 'F', '1976-05-29', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (108, 'Mel Ketteringham', 'M', '1970-08-14', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (109, 'Verne Trousdale', 'M', '1972-09-20', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (110, 'Kelbee Fordyce', 'M', '1986-04-08', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (111, 'Milton Marieton', 'M', '1997-07-17', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (112, 'Marena Niezen', 'F', '1992-03-15', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (113, 'Jasmine Duckers', 'F', '1976-08-15', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (114, 'Modesta Mingardo', 'F', '1967-06-29', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (115, 'Sacha Smithe', 'F', '1977-04-04', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (116, 'Tansy Eveleigh', 'F', '1996-04-03', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (117, 'Jelene MacCumeskey', 'F', '1972-01-14', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (118, 'Binni Killingsworth', 'F', '1998-01-15', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (119, 'Cazzie Gussie', 'M', '1985-01-18', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (120, 'Gabriel O''Drought', 'M', '1988-01-23', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (121, 'Meredith Shortin', 'F', '1970-12-24', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (122, 'Etan Berney', 'M', '1983-12-09', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (123, 'Wilhelmina Camier', 'F', '1968-10-14', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (124, 'Courtnay Sargint', 'F', '1975-03-27', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (125, 'Timmie Rockell', 'F', '1977-09-16', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (126, 'Frants Sandaver', 'M', '1980-12-21', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (127, 'Eugen Choppen', 'M', '1982-07-14', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (128, 'Arnold Leyman', 'M', '1987-01-20', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (129, 'Ariel Riddle', 'M', '1973-04-24', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (130, 'Vince Chatterton', 'M', '1998-01-05', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (131, 'Zachery Surcombe', 'M', '1982-10-25', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (132, 'Arabella Trussell', 'F', '1986-10-08', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (133, 'Conrado Hearns', 'M', '1970-03-11', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (134, 'Leonid Le Galle', 'M', '1981-12-02', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (135, 'Norbie Geddes', 'M', '1983-12-02', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (136, 'Octavius Hosburn', 'M', '1975-06-22', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (137, 'Diarmid Keymer', 'M', '1974-10-03', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (138, 'Simeon Maddern', 'M', '1997-06-16', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (139, 'Antone Kerman', 'M', '1979-11-09', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (140, 'Tabor Sahnow', 'M', '1973-06-21', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (141, 'Dore Clyant', 'M', '1967-09-30', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (142, 'Chrystal Inchboard', 'F', '1995-10-21', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (143, 'Merrel Ferrao', 'M', '1991-01-02', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (144, 'Fredi Fadian', 'F', '1984-02-05', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (145, 'Leigh Girling', 'M', '1971-03-11', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (146, 'Cynthie Staddom', 'F', '1967-08-22', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (147, 'Lazaro Chansonne', 'M', '1988-02-29', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (148, 'Rikki Laurence', 'F', '1989-12-20', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (149, 'Gayelord Reglar', 'M', '1995-10-12', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (150, 'Marge Markova', 'F', '1989-11-12', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (151, 'Rolfe Karsh', 'M', '1983-01-31', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (152, 'Selby Scorthorne', 'M', '1967-02-26', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (153, 'Marilee Doppler', 'F', '1989-10-20', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (154, 'Suzy Strewther', 'F', '1998-07-09', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (155, 'Addy Wainwright', 'F', '1985-07-14', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (156, 'Jonathon Petrak', 'M', '1968-12-20', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (157, 'Spike Jaan', 'M', '1972-07-19', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (158, 'Luce Heersema', 'M', '1967-11-10', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (159, 'Jesselyn Boichat', 'F', '1991-07-30', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (160, 'Cyril Morecomb', 'M', '1996-12-12', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (161, 'Waylen Freckelton', 'M', '1994-08-13', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (162, 'Jess Vallens', 'M', '1983-01-31', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (163, 'Ellery Long', 'M', '1979-07-25', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (164, 'Greggory Axworthy', 'M', '1978-06-29', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (165, 'Millisent O''Bradane', 'F', '1981-07-17', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (166, 'Cordula Tisun', 'F', '1977-12-29', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (167, 'Minor Coatts', 'M', '1975-02-19', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (168, 'Twila McGinley', 'F', '1986-05-21', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (169, 'Michelle Janca', 'F', '1967-10-22', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (170, 'Garrot Proger', 'M', '1994-03-07', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (171, 'Raven Daymond', 'F', '1999-03-01', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (172, 'Petronilla Tinmouth', 'F', '1995-12-01', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (173, 'Mireille Morrish', 'F', '1994-02-04', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (174, 'Farica Willas', 'F', '1970-04-10', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (175, 'Lindsey Hemeret', 'M', '1975-04-25', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (176, 'Spense Bourrel', 'M', '1982-07-04', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (177, 'Ulrikaumeko Parrett', 'F', '1967-05-19', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (178, 'Pietrek Kun', 'M', '1991-05-21', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (179, 'Dyan Aimson', 'F', '1994-05-21', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (180, 'Candy Bernholt', 'F', '1997-12-15', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (181, 'Edeline Gryglewski', 'F', '1982-08-01', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (182, 'Vilma Goodrich', 'F', '1977-09-07', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (183, 'Gerardo Flicker', 'M', '1974-04-16', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (184, 'Quill Woolcocks', 'M', '1987-03-22', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (185, 'Pammie Glaum', 'F', '1969-01-13', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (186, 'Martyn Haffard', 'M', '1979-12-30', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (187, 'Ade O''Rudden', 'M', '1979-06-02', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (188, 'Caria Gandey', 'F', '1995-11-05', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (189, 'Demetra Hammor', 'F', '1990-02-15', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (190, 'Odie Colquyte', 'M', '1981-02-03', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (191, 'Rachelle Dukesbury', 'F', '1970-12-26', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (192, 'Rebecka Vasilmanov', 'F', '1977-03-13', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (193, 'Kinna Wightman', 'F', '1994-12-31', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (194, 'Elwyn Rastrick', 'M', '1996-06-02', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (195, 'Ethan Jerrard', 'M', '1988-07-08', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (196, 'Ree Pretsel', 'F', '1972-10-10', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (197, 'Tresa Kalkofer', 'F', '1988-09-27', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (198, 'Violet McGilbon', 'F', '1972-08-27', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (199, 'Adey Martinovic', 'F', '1972-10-10', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (200, 'Gregor Robley', 'M', '1994-05-27', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (201, 'Ruddy Ruppele', 'M', '1975-05-01', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (202, 'Lonny Gruczka', 'M', '1967-08-23', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (203, 'Sabina Jeffcoat', 'F', '1977-01-28', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (204, 'Amalia Macquire', 'F', '1976-06-01', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (205, 'Giffard Szanto', 'M', '1987-06-09', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (206, 'Emile Southern', 'M', '1968-04-02', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (207, 'Joelle Spackman', 'F', '1983-11-15', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (208, 'Cornelius Oakden', 'M', '1969-04-17', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (209, 'Glennis Fenner', 'F', '1979-07-05', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (210, 'Davie Iacovielli', 'M', '1969-12-09', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (211, 'Gabriella Berka', 'F', '1986-02-11', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (212, 'Zachery Duckett', 'M', '1986-10-02', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (213, 'Heloise Perryman', 'F', '1989-12-23', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (214, 'Wilfred Meah', 'M', '1999-07-06', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (215, 'Wilhelmina Lomond', 'F', '1968-08-18', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (216, 'Zach Skirvane', 'M', '1981-08-18', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (217, 'Brinna Ferraresi', 'F', '1977-11-22', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (218, 'Artemis Lippitt', 'M', '1972-07-24', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (219, 'Adrienne Ashenhurst', 'F', '1989-11-19', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (220, 'Irwinn Soro', 'M', '1986-01-21', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (221, 'Marrilee Birkby', 'F', '1982-09-22', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (222, 'Mile Lamasna', 'M', '1976-02-26', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (223, 'Palmer Searight', 'M', '1979-05-20', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (224, 'Renee Simo', 'F', '1969-09-08', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (225, 'Haywood Bourne', 'M', '1982-10-29', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (226, 'Lainey Mounce', 'F', '1976-01-13', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (227, 'Samuele Freezor', 'M', '1976-09-12', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (228, 'Buffy Beldon', 'F', '1988-12-22', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (229, 'Leda Jessopp', 'F', '1995-06-14', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (230, 'Jeddy Aumerle', 'M', '1972-05-19', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (231, 'Geoffrey Eyckel', 'M', '1986-08-26', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (232, 'Roze Oxburgh', 'F', '1980-05-10', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (233, 'Kessiah Jakobssen', 'F', '1967-09-08', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (234, 'Lind Sambedge', 'F', '1985-06-27', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (235, 'Justin Orvis', 'M', '1987-10-07', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (236, 'Duncan Francke', 'M', '1986-04-05', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (237, 'Melodie Radwell', 'F', '1978-07-19', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (238, 'Taylor Calveley', 'M', '1980-12-18', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (239, 'Brent Benech', 'M', '1978-06-05', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (240, 'Kassandra Melrose', 'F', '1985-01-03', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (241, 'Alf Scrivens', 'M', '1973-05-30', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (242, 'Bronson Allsepp', 'M', '1987-05-19', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (243, 'Lois Fitkin', 'F', '1991-01-09', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (244, 'Grantley Moynham', 'M', '1984-09-01', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (245, 'Lee Pidduck', 'M', '1987-04-22', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (246, 'Velma Yuryaev', 'F', '1995-08-27', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (247, 'Tobye Hamby', 'F', '1975-05-23', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (248, 'Jannel Pohls', 'F', '1991-06-15', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (249, 'Tammy Bertenshaw', 'M', '1967-02-01', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (250, 'Brooks Sandes', 'M', '1987-03-16', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (251, 'Ruperta Curless', 'F', '1983-05-02', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (252, 'Abbott MacIlurick', 'M', '1995-07-17', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (253, 'Izak Hourigan', 'M', '1977-11-20', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (254, 'Nathalia Monday', 'F', '1985-11-08', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (255, 'Florie Kepling', 'F', '1982-06-11', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (256, 'Ekaterina Samwayes', 'F', '1990-05-04', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (257, 'Arty Ivanichev', 'M', '1988-05-09', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (258, 'Nicole Raraty', 'F', '1983-02-02', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (259, 'Garret McDunlevy', 'M', '1970-05-12', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (260, 'Brigitta Bruckner', 'F', '1999-01-29', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (261, 'Ronni Duncklee', 'F', '1983-05-14', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (262, 'Chantalle Gasnoll', 'F', '1982-08-22', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (263, 'Dare Kenrat', 'M', '1999-11-14', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (264, 'Quill Whitcher', 'M', '1996-06-01', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (265, 'Ricardo Cammish', 'M', '1972-07-08', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (266, 'Tybalt Gyorgy', 'M', '1978-09-13', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (267, 'Waldon Bevis', 'M', '1980-10-18', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (268, 'Aubert Dmytryk', 'M', '1983-05-02', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (269, 'Bernette Leindecker', 'F', '1976-02-16', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (270, 'Blake Ucceli', 'M', '1969-02-02', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (271, 'Zachery Hanniger', 'M', '1991-06-29', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (272, 'Caresse Drake', 'F', '1984-02-23', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (273, 'Elizabet Behnecken', 'F', '1981-06-07', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (274, 'Leon Pretsel', 'M', '1995-06-21', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (275, 'Kaila Newcomen', 'F', '1989-12-14', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (276, 'Ash Eatttok', 'M', '1994-10-03', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (277, 'Leshia Suffe', 'F', '1994-03-12', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (278, 'Dulcine Raynes', 'F', '1982-02-15', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (279, 'Katrinka Olsson', 'F', '1997-07-15', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (280, 'Law Ledwich', 'M', '1982-05-02', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (281, 'Farley Szimon', 'M', '1996-11-24', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (282, 'Pippa Follacaro', 'F', '1988-04-26', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (283, 'Nehemiah Ivons', 'M', '1996-07-01', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (284, 'Simonne Dyett', 'F', '1980-04-17', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (285, 'Rosalyn Veazey', 'F', '1989-07-04', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (286, 'Byrom Lob', 'M', '1967-12-28', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (287, 'Emmet O''Hegertie', 'M', '1997-10-30', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (288, 'Terese Mulderrig', 'F', '1998-07-10', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (289, 'Clementius Enoch', 'M', '1969-11-17', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (290, 'Noni Collings', 'F', '1999-07-05', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (291, 'Leela Pottle', 'F', '1988-05-04', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (292, 'Roselin Tynemouth', 'F', '1994-10-25', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (293, 'Ibrahim Chrstine', 'M', '1989-04-18', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (294, 'Joane Waddoups', 'F', '1972-05-15', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (295, 'Brena Roly', 'F', '1997-05-30', 'Vila Meriti');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (296, 'Vevay Rooney', 'F', '1984-12-11', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (297, 'Flore Lewington', 'F', '1971-11-17', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (298, 'Issy McTurley', 'F', '1975-02-28', 'Paulicéia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (299, 'Bride Langshaw', 'F', '1981-05-01', 'Centenário');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (300, 'Kaiser Whittleton', 'M', '1977-11-22', 'Vila Meriti');
